export const VacationCodeErrors = {
  INVALID_NEXT_YEAR_VACATION_DAYS_REQUEST: 'INVALID_NEXT_YEAR_VACATION_DAYS_REQUEST',
  VACATION_RANGE_CLOSED: 'VACATION_RANGE_CLOSED',
  VACATION_BEFORE_HIRING_DATE: 'VACATION_BEFORE_HIRING_DATE',
  VACATION_REQUEST_OVERLAPS: 'VACATION_REQUEST_OVERLAPS',
  VACATION_REQUEST_EMPTY: 'VACATION_REQUEST_EMPTY'
} as const
