export const ActivityCodeErrors = {
  ACTIVITY_BEFORE_HIRING_DATE: 'ACTIVITY_BEFORE_HIRING_DATE',
  ACTIVITY_TIME_OVERLAPS: 'ACTIVITY_TIME_OVERLAPS',
  ACTIVITY_PERIOD_CLOSED: 'ACTIVITY_PERIOD_CLOSED',
  CLOSED_PROJECT: 'CLOSED_PROJECT',
  MAX_REGISTRABLE_HOURS_LIMIT_EXCEEDED: 'MAX_REGISTRABLE_HOURS_LIMIT_EXCEEDED',
  INVALID_ACTIVITY_APPROVAL_STATE: 'INVALID_ACTIVITY_APPROVAL_STATE'
} as const
