export const ActivityCodeErrors = {
  ACTIVITY_BEFORE_HIRING_DATE: 'ACTIVITY_BEFORE_HIRING_DATE',
  ACTIVITY_TIME_OVERLAPS: 'ACTIVITY_TIME_OVERLAPS',
  ACTIVITY_PERIOD_CLOSED: 'ACTIVITY_PERIOD_CLOSED',
  ACTIVITY_BEFORE_PROJECT_CREATION_DATE: 'ACTIVITY_BEFORE_PROJECT_CREATION_DATE',
  CLOSED_PROJECT: 'CLOSED_PROJECT',
  MAX_REGISTRABLE_TIME_LIMIT_EXCEEDED: 'MAX_REGISTRABLE_TIME_LIMIT_EXCEEDED',
  MAX_REGISTRABLE_TIME_PER_ACTIVITY_LIMIT_EXCEEDED:
    'MAX_REGISTRABLE_TIME_PER_ACTIVITY_LIMIT_EXCEEDED',
  INVALID_ACTIVITY_APPROVAL_STATE: 'INVALID_ACTIVITY_APPROVAL_STATE',
  BLOCKED_PROJECT: 'BLOCKED_PROJECT'
} as const
