export enum CodeErrors {
  ACTIVITY_BEFORE_HIRING_DATE = 'ACTIVITY_BEFORE_HIRING_DATE',
  ACTIVITY_TIME_OVERLAPS = 'ACTIVITY_TIME_OVERLAPS',
  ACTIVITY_PERIOD_CLOSED = 'ACTIVITY_PERIOD_CLOSED',
  CLOSED_PROJECT = 'CLOSED_PROJECT',
  INVALID_NEXT_YEAR_VACATION_DAYS_REQUEST = 'INVALID_NEXT_YEAR_VACATION_DAYS_REQUEST',
  VACATION_RANGE_CLOSED = 'VACATION_RANGE_CLOSED',
  VACATION_BEFORE_HIRING_DATE = 'VACATION_BEFORE_HIRING_DATE',
  VACATION_REQUEST_OVERLAPS = 'VACATION_REQUEST_OVERLAPS',
  VACATION_REQUEST_EMPTY = 'VACATION_REQUEST_EMPTY'
}
