export enum CodeErrors {
  ACTIVITY_TIME_OVERLAPS = 'ACTIVITY_TIME_OVERLAPS',
  CLOSED_PROJECT = 'CLOSED_PROJECT',
  ACTIVITY_PERIOD_CLOSED = 'ACTIVITY_PERIOD_CLOSED',
  INVALID_NEXT_YEAR_VACATION_DAYS_REQUEST = 'INVALID_NEXT_YEAR_VACATION_DAYS_REQUEST',
  VACATION_RANGE_CLOSED = 'VACATION_RANGE_CLOSED'
}