# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Binnacle CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test

    steps:
      - name: Clone repository
        uses: actions/checkout@v2


      - name: Use Node.js 15
        uses: actions/setup-node@v2
        with:
          node-version: '15.14.0'
          # https://github.com/actions/setup-node#caching-packages-dependencies
          # cache dependencies
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Run the tests and generate coverage report
        run: npm run test:unit:ci
