# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Binnacle CD
on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js 15
        uses: actions/setup-node@v2
        with:
          node-version: '15.14.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Run Test
        run: npm run test:unit:ci

      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Get package version
        run: |
          NEXT_RELEASE=$(jq '.version' package.json | sed 's/-SNAPSHOT.0//' | xargs npm version --no-git-tag-version | sed 's/v//')
          echo "NEXT_RELEASE=$NEXT_RELEASE" >> $GITHUB_ENV
        shell: bash

      - name: Build Integration
        run: npm run build:int

      - name: Build Production
        run: npm run build:prod

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'binnacle_front_*.zip'
          generateReleaseNotes: true
          tag: ${{ env.NEXT_RELEASE }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create SNAPSHOT
        run: npm version prerelease --preid SNAPSHOT --no-git-tag-version

      - name: Update version in remote
        run: |
          git add package.json
          git add package-lock.json
          git commit -m "chore: prepare snapshot"
          git push
