name: Binnacle CD
on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Get package version
        run: |
          NEXT_RELEASE=$(jq '.version' package.json | sed 's/-SNAPSHOT.0//' | xargs npm version --no-git-tag-version | sed 's/v//')
          echo "NEXT_RELEASE=$NEXT_RELEASE" >> $GITHUB_ENV
        shell: bash

      - name: Build Integration
        run: npm run build:int

      - name: Build Production
        run: npm run build:prod

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'binnacle_front_*.zip'
          generateReleaseNotes: true
          tag: ${{ env.NEXT_RELEASE }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create SNAPSHOT
        run: npm version prerelease --preid SNAPSHOT --no-git-tag-version

      - name: Update version in remote
        run: |
          git add package.json
          git add package-lock.json
          git commit -m "chore: prepare snapshot"
          git push
